# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_year', models.IntegerField(max_length=10)),
                ('car_ratings', models.IntegerField(max_length=10)),
                ('car_score', models.FloatField(max_length=10)),
            ],
        ),
    ]
